curl -s -w ' -> %{http_code}\n' -X POST http://localhost:3000/api/dogs -H 'Content-Type: application/json' -d '{"name":"Füles","is_girl":true,"born_at":"2023-06-15","breed":"Tacskó","weight_kg":5.8,"color":"barna","adopted_at":null,"owner_id":2}'
curl -s -w ' -> %{http_code}\n' -X POST http://localhost:3000/api/dogs -H 'Content-Type: application/json' -d '{"name":"Gazdátlan","is_girl":false,"born_at":"2022-01-01"}'
curl -s -w ' -> %{http_code}\n' -X POST http://localhost:3000/api/dogs -H 'Content-Type: application/json' -d '{"is_girl":true,"born_at":"2022-01-01"}'
curl -s -w ' -> %{http_code}\n' -X POST http://localhost:3000/api/dogs -H 'Content-Type: application/json' -d '{"name":"","is_girl":true,"born_at":"2022-01-01"}'
curl -s -w ' -> %{http_code}\n' -X POST http://localhost:3000/api/dogs -H 'Content-Type: application/json' -d '{"name":"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa","is_girl":true,"born_at":"2022-01-01"}'
curl -s -w ' -> %{http_code}\n' -X POST http://localhost:3000/api/dogs -H 'Content-Type: application/json' -d '{"name":"x","born_at":"2022-01-01"}'
curl -s -w ' -> %{http_code}\n' -X POST http://localhost:3000/api/dogs -H 'Content-Type: application/json' -d '{"name":"x","is_girl":"igen","born_at":"2022-01-01"}'
curl -s -w ' -> %{http_code}\n' -X POST http://localhost:3000/api/dogs -H 'Content-Type: application/json' -d '{"name":"x","is_girl":true}'
curl -s -w ' -> %{http_code}\n' -X POST http://localhost:3000/api/dogs -H 'Content-Type: application/json' -d '{"name":"x","is_girl":true,"born_at":"2023-13-45"}'
curl -s -w ' -> %{http_code}\n' -X POST http://localhost:3000/api/dogs -H 'Content-Type: application/json' -d '{"name":"x","is_girl":true,"born_at":"2999-01-01"}'
curl -s -w ' -> %{http_code}\n' -X POST http://localhost:3000/api/dogs -H 'Content-Type: application/json' -d '{"name":"x","is_girl":true,"born_at":"2022-01-01","breed":"bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb"}'
curl -s -w ' -> %{http_code}\n' -X POST http://localhost:3000/api/dogs -H 'Content-Type: application/json' -d '{"name":"x","is_girl":true,"born_at":"2022-01-01","weight_kg":0}'
curl -s -w ' -> %{http_code}\n' -X POST http://localhost:3000/api/dogs -H 'Content-Type: application/json' -d '{"name":"x","is_girl":true,"born_at":"2022-01-01","weight_kg":-3}'
curl -s -w ' -> %{http_code}\n' -X POST http://localhost:3000/api/dogs -H 'Content-Type: application/json' -d '{"name":"x","is_girl":true,"born_at":"2022-01-01","weight_kg":"abc"}'
curl -s -w ' -> %{http_code}\n' -X POST http://localhost:3000/api/dogs -H 'Content-Type: application/json' -d '{"name":"x","is_girl":true,"born_at":"2022-01-01","color":"ccccccccccccccccccccccccccccccc"}'
curl -s -w ' -> %{http_code}\n' -X POST http://localhost:3000/api/dogs -H 'Content-Type: application/json' -d '{"name":"x","is_girl":true,"born_at":"2022-01-01","adopted_at":"nem-datum"}'
curl -s -w ' -> %{http_code}\n' -X POST http://localhost:3000/api/dogs -H 'Content-Type: application/json' -d '{"name":"x","is_girl":true,"born_at":"2022-01-01","owner_id":0}'
curl -s -w ' -> %{http_code}\n' -X POST http://localhost:3000/api/dogs -H 'Content-Type: application/json' -d '{"name":"x","is_girl":true,"born_at":"2022-01-01","owner_id":999999}'
curl -s -w ' -> %{http_code}\n' -X POST http://localhost:3000/api/dogs -H 'Content-Type: application/json' -d '{"name":'

curl -s -w ' -> %{http_code}\n' 'http://localhost:3000/api/dogs'
curl -s -w ' -> %{http_code}\n' 'http://localhost:3000/api/dogs?breed=Puli'
curl -s -w ' -> %{http_code}\n' 'http://localhost:3000/api/dogs?is_girl=1'
curl -s -w ' -> %{http_code}\n' 'http://localhost:3000/api/dogs?is_girl=0'
curl -s -w ' -> %{http_code}\n' 'http://localhost:3000/api/dogs?owner_id=1'
curl -s -w ' -> %{http_code}\n' 'http://localhost:3000/api/dogs?has_owner=true'
curl -s -w ' -> %{http_code}\n' 'http://localhost:3000/api/dogs?has_owner=false'
curl -s -w ' -> %{http_code}\n' 'http://localhost:3000/api/dogs?min_weight=10'
curl -s -w ' -> %{http_code}\n' 'http://localhost:3000/api/dogs?max_weight=15'
curl -s -w ' -> %{http_code}\n' 'http://localhost:3000/api/dogs?min_weight=10&max_weight=20'
curl -s -w ' -> %{http_code}\n' 'http://localhost:3000/api/dogs?search=Bo'
curl -s -w ' -> %{http_code}\n' 'http://localhost:3000/api/dogs?sort=weight_kg&order=desc'
curl -s -w ' -> %{http_code}\n' 'http://localhost:3000/api/dogs?sort=born_at&order=asc'
curl -s -w ' -> %{http_code}\n' 'http://localhost:3000/api/dogs?sort=name&order=desc'
curl -s -w ' -> %{http_code}\n' 'http://localhost:3000/api/dogs?limit=1&offset=1'
curl -s -w ' -> %{http_code}\n' 'http://localhost:3000/api/dogs?min_weight=abc'
curl -s -w ' -> %{http_code}\n' 'http://localhost:3000/api/dogs?max_weight=abc'
curl -s -w ' -> %{http_code}\n' 'http://localhost:3000/api/dogs?is_girl=2'
curl -s -w ' -> %{http_code}\n' 'http://localhost:3000/api/dogs?has_owner=maybe'
curl -s -w ' -> %{http_code}\n' 'http://localhost:3000/api/dogs?owner_id=abc'
curl -s -w ' -> %{http_code}\n' 'http://localhost:3000/api/dogs?limit=0'
curl -s -w ' -> %{http_code}\n' 'http://localhost:3000/api/dogs?limit=101'
curl -s -w ' -> %{http_code}\n' 'http://localhost:3000/api/dogs?offset=-1'
curl -s -w ' -> %{http_code}\n' 'http://localhost:3000/api/dogs?sort=foo'
curl -s -w ' -> %{http_code}\n' 'http://localhost:3000/api/dogs?order=foo'

curl -s -w ' -> %{http_code}\n' http://localhost:3000/api/dogs/1
curl -s -w ' -> %{http_code}\n' http://localhost:3000/api/dogs/999999
curl -s -w ' -> %{http_code}\n' http://localhost:3000/api/dogs/abc
curl -s -w ' -> %{http_code}\n' http://localhost:3000/api/dogs/0
curl -s -w ' -> %{http_code}\n' http://localhost:3000/api/dogs/-5

curl -s -w ' -> %{http_code}\n' 'http://localhost:3000/api/dogs/stats/by-breed'
curl -s -w ' -> %{http_code}\n' 'http://localhost:3000/api/dogs/stats/by-breed?min_count=2'
curl -s -w ' -> %{http_code}\n' 'http://localhost:3000/api/dogs/stats/by-breed?with_owners_only=true'
curl -s -w ' -> %{http_code}\n' 'http://localhost:3000/api/dogs/stats/by-breed?with_owners_only=false'
curl -s -w ' -> %{http_code}\n' 'http://localhost:3000/api/dogs/stats/by-breed?min_count=2&with_owners_only=true'
curl -s -w ' -> %{http_code}\n' 'http://localhost:3000/api/dogs/stats/by-breed?min_count=0'
curl -s -w ' -> %{http_code}\n' 'http://localhost:3000/api/dogs/stats/by-breed?min_count=abc'
curl -s -w ' -> %{http_code}\n' 'http://localhost:3000/api/dogs/stats/by-breed?with_owners_only=foo'

curl -s -w ' -> %{http_code}\n' -X PUT http://localhost:3000/api/dogs/1 -H 'Content-Type: application/json' -d '{"name":"Bodri","is_girl":false,"born_at":"2019-03-12","breed":"Puli","weight_kg":13.5,"color":"fekete","adopted_at":"2019-06-01","owner_id":1}'
curl -s -w ' -> %{http_code}\n' -X PUT http://localhost:3000/api/dogs/1 -H 'Content-Type: application/json' -d '{"name":"Bodri","is_girl":false,"born_at":"2019-03-12","breed":"Puli","weight_kg":13.5,"color":"fekete","adopted_at":null,"owner_id":null}'
curl -s -w ' -> %{http_code}\n' -X PUT http://localhost:3000/api/dogs/1 -H 'Content-Type: application/json' -d '{"is_girl":false,"born_at":"2019-03-12","breed":"Puli","weight_kg":13.5,"color":"fekete","adopted_at":null,"owner_id":null}'
curl -s -w ' -> %{http_code}\n' -X PUT http://localhost:3000/api/dogs/1 -H 'Content-Type: application/json' -d '{"name":"x","is_girl":false,"born_at":"2019-03-12","breed":"Puli","color":"fekete","adopted_at":null,"owner_id":null}'
curl -s -w ' -> %{http_code}\n' -X PUT http://localhost:3000/api/dogs/1 -H 'Content-Type: application/json' -d '{"name":"x","is_girl":false,"born_at":"2019-03-12","breed":"Puli","weight_kg":13.5,"color":"fekete","adopted_at":null}'
curl -s -w ' -> %{http_code}\n' -X PUT http://localhost:3000/api/dogs/1 -H 'Content-Type: application/json' -d '{"name":"x","is_girl":false,"born_at":"2999-01-01","breed":"Puli","weight_kg":13.5,"color":"fekete","adopted_at":null,"owner_id":null}'
curl -s -w ' -> %{http_code}\n' -X PUT http://localhost:3000/api/dogs/999999 -H 'Content-Type: application/json' -d '{"name":"x","is_girl":false,"born_at":"2019-03-12","breed":"Puli","weight_kg":13.5,"color":"fekete","adopted_at":null,"owner_id":null}'
curl -s -w ' -> %{http_code}\n' -X PUT http://localhost:3000/api/dogs/1 -H 'Content-Type: application/json' -d '{"name":"x","is_girl":false,"born_at":"2019-03-12","breed":"Puli","weight_kg":13.5,"color":"fekete","adopted_at":null,"owner_id":999999}'
curl -s -w ' -> %{http_code}\n' -X PUT http://localhost:3000/api/dogs/abc -H 'Content-Type: application/json' -d '{"name":"x","is_girl":false,"born_at":"2019-03-12","breed":"Puli","weight_kg":13.5,"color":"fekete","adopted_at":null,"owner_id":null}'

curl -s -w ' -> %{http_code}\n' -X PUT http://localhost:3000/api/dogs/1/owner -H 'Content-Type: application/json' -d '{"owner_id":3}'
curl -s -w ' -> %{http_code}\n' -X PUT http://localhost:3000/api/dogs/1/owner -H 'Content-Type: application/json' -d '{"owner_id":2}'
curl -s -w ' -> %{http_code}\n' -X PUT http://localhost:3000/api/dogs/1/owner -H 'Content-Type: application/json' -d '{"owner_id":null}'
curl -s -w ' -> %{http_code}\n' -X PUT http://localhost:3000/api/dogs/1/owner -H 'Content-Type: application/json' -d '{}'
curl -s -w ' -> %{http_code}\n' -X PUT http://localhost:3000/api/dogs/1/owner -H 'Content-Type: application/json' -d '{"owner_id":"abc"}'
curl -s -w ' -> %{http_code}\n' -X PUT http://localhost:3000/api/dogs/999999/owner -H 'Content-Type: application/json' -d '{"owner_id":1}'
curl -s -w ' -> %{http_code}\n' -X PUT http://localhost:3000/api/dogs/1/owner -H 'Content-Type: application/json' -d '{"owner_id":999999}'
curl -s -w ' -> %{http_code}\n' -X PUT http://localhost:3000/api/dogs/abc/owner -H 'Content-Type: application/json' -d '{"owner_id":1}'

curl -s -w ' -> %{http_code}\n' -X DELETE http://localhost:3000/api/dogs/abc
curl -s -w ' -> %{http_code}\n' -X DELETE http://localhost:3000/api/dogs/999999
curl -s -w ' -> %{http_code}\n' -X DELETE http://localhost:3000/api/dogs/1
curl -s -w ' -> %{http_code}\n' http://localhost:3000/api/dogs/1